version: '3.8'

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  geth:
    image: matterlabs/geth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./volumes/geth:/var/lib/geth/data
    environment:
      PLUGIN_CONFIG: fast

  dev-liquidity-token-watcher:
    image: matterlabs/dev-liquidity-token-watcher:latest
    env_file:
      - ./etc/env/docker.env
    ports:
      - "9975:9975"
    volumes:
      - ./etc/tokens:/etc/tokens

  dev-ticker:
    image: matterlabs/dev-ticker:latest
    ports:
      - "9876:9876"
    volumes:
      - ./etc/tokens:/etc/tokens
